[package]
name = "rmbs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
minreq = { version = "2.12.0", features = ["https"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
